### ISSUE TITLE
Errores durante el proceso de instalación

### ISSUE THREAD

**Issue by 3rn3st0** [LuisAlejandro/subliminal-vim#25]
```
Traceback (most recent call last):
  File "/home/ernestoch/gits/subliminal-vim/bundle/YouCompleteMe/third_party/ycmd/build.py", line 371, in BuildYcmdLib
    subprocess.check_call( build_command )
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command '['cmake', '--build', '.', '--target', 'ycm_core', '--', '-j', '4']' returned non-zero exit status 2


ERROR: The build failed.

NOTE: It is *highly* unlikely that this is a bug but rather
that this is a problem with the configuration of your system
or a missing dependency. Please carefully read CONTRIBUTING.md
and if you're sure that it is a bug, please raise an issue on the
issue tracker, including the entire output of this script
and the invocation line used to run it.

Traceback (most recent call last):
  File "install.py", line 44, in <module>
    Main()
  File "install.py", line 33, in Main
    subprocess.check_call( [ python_binary, build_file ] + sys.argv[1:] )
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/python', u'/home/ernestoch/gits/subliminal-vim/bundle/YouCompleteMe/third_party/ycmd/build.py', '--clang-completer', '--gocode-completer', '--tern-completer']' returned non-zero exit status 1
Makefile:51: recipe for target 'build' failed
make: *** [build] Error 1
```

**Comment by LuisAlejandro** [comment]
Gracias por el reporte @3rn3st0, cuando puedas envía el log completo para poder debuguear. Saludos.

**Comment by 3rn3st0** [comment]
Revisa @LuisAlejandro, envié todo lo que me bota la consola durante el proceso. Espero que esta vez sea más útil la información :thumbsup: :grimacing:

**Comment by LuisAlejandro** [comment]
Perfecto, al script de instalación le falta incluir la dependencia `python-dev`, coloca esto en consola y continúa por favor.

```
apt-get install python-dev
```
